---
jobs:
  build:
    docker:
      -
        image: circleci/php
    working_directory: ~/jinya
    steps:
      - checkout
      -
        restore_cache:
          keys:
            - "v1-dependencies-{{ checksum \"composer.json\" }}"
            - v1-dependencies-
      -
        run: "composer install -n --prefer-dist --no-scripts --no-dev"
      -
        save_cache:
          key: "v1-dependencies-{{ checksum \"composer.json\" }}"
          paths:
            - ./vendor
      -
        run:
          command: |
            mkdir -p ~/dist
            cd ~/jinya/
            tar -zcf ~/dist/jinya-api.tar.gz *
      -
        persist_to_workspace:
          paths:
            - jinya-api.tar.gz
          root: ~/dist
  deploy:
    docker:
      -
        image: circleci/php
    steps:
      -
        attach_workspace:
          at: ~/jinya/
      -
        run:
          command: |
            scp -oStrictHostKeyChecking=no -r ~/dist/jinya-api.tar.gz $DEPLOY_LOGIN@$DEPLOY_SERVER:$DEPLOY_TARGET/jinya-api.tar.gz
            ssh -oStrictHostKeyChecking=no "tar -zxf $DEPLOY_TARGET/jinya-api.tar.gz -C $DEPLOY_TARGET/"
          name: "Deploy via SCP"
    working_directory: ~/jinya
version: 2
workflows:
  stable:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      -
        deploy:
          requires:
            - build
  version: 2
