---
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: ~/jinya
    steps:
      - checkout
      -
        run:
          command: |
            sudo chmod -R 777 /usr/
            export GOARCH=386
            export GOOS=linux
            go get github.com/scorredoira/email
            go build -i -o /home/circleci/jinya-api .
      -
        persist_to_workspace:
          paths:
          - jinya-api
          root: ~/
  deploy:
    docker:
      - image: circleci/golang
    steps:
      -
        attach_workspace:
          at: ~/jinya/
      -
        run:
          command: |
            scp -oStrictHostKeyChecking=no -r ~/jinya/jinya-api.tar.gz $DEPLOY_LOGIN@$DEPLOY_SERVER:$DEPLOY_TARGET/jinya-api
          name: "Deploy via SCP"
    working_directory: ~/jinya
version: 2
workflows:
  stable:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      -
        deploy:
          requires:
            - build
  version: 2
